/**
 * The job specification: one JSON file that says which graph to run, how
 * long, over which grid of settings, what to record and how to summarise it.
 *
 * The spec is the whole contract between the caller (a shell, a container
 * entrypoint, a serverless job platform, the `factory` MCP slot) and the
 * runner. Nothing else is read: no environment-specific knowledge lives in
 * the runner, so the same spec produces the same outputs wherever it runs.
 *
 * Validation is strict and the errors name the offending path, because a
 * spec is typed by hand or generated by an agent, and a silently ignored
 * key is worse than a refused job.
 */

/** A setting applied to one node before a run. */
export type { IDocumentSetting as NodeSetting } from "spikypanda-core";
import type { IDocumentSetting as NodeSetting } from "spikypanda-core";

/** One axis of the sweep grid. Either an explicit list or an inclusive range. */
export interface GridAxis {
    readonly node: string;
    readonly property: string;
    readonly values?: ReadonlyArray<unknown>;
    readonly range?: { readonly from: number; readonly to: number; readonly step: number };
}

/** A value read from a node instance after every tick. */
export interface RecordField {
    readonly node: string;
    readonly property: string;
    /** Column name in the outputs. Defaults to `<node>.<property>`. */
    readonly as?: string;
}

/**
 * Lock-in frequency source: a constant in hertz, or the window mean of a
 * recorded field, read as an angular velocity (rad/s, divided by 2*pi) or
 * directly as hertz.
 */
export type FrequencySource = { readonly hz: number } | { readonly fromField: string; readonly kind: "angular" | "hz" };

export interface SummaryStat {
    /** Recorded column (`as` of a record entry). */
    readonly field: string;
    readonly stat: "mean" | "min" | "max" | "rms" | "lockin";
    /** Required for `lockin`. */
    readonly frequency?: FrequencySource;
    /** Output column name. Defaults to `<field>_<stat>`. */
    readonly as?: string;
}

export interface RunSettings {
    /** Tick period in simulated seconds. */
    readonly dt: number;
    /** Simulated duration of one grid point, in seconds. */
    readonly duration: number;
    /** Samples before this time are left out of the summary window. */
    readonly settle: number;
}

export interface OutputSettings {
    /** Directory the job writes into (a `<name>/` folder is created inside). */
    readonly dir?: string;
    /** Also write every tick of every point as JSON lines (the training set). */
    readonly samples?: boolean;
}

export interface SweepSpec {
    readonly version: 1;
    readonly job: "sweep";
    /** Output folder name and manifest label. */
    readonly name: string;
    /** Path to the `.spikypanda` document, absolute or relative to the spec file. */
    readonly graph: string;
    readonly run: RunSettings;
    /** Applied to every point, before the grid. */
    readonly set?: ReadonlyArray<NodeSetting>;
    readonly grid?: ReadonlyArray<GridAxis>;
    readonly record: ReadonlyArray<RecordField>;
    readonly summary?: ReadonlyArray<SummaryStat>;
    readonly outputs?: OutputSettings;
}

/** A dataset column: a name, optionally rescaled (`value * scale + offset`) before use. */
export interface ColumnRef {
    readonly column: string;
    readonly scale: number;
    readonly offset: number;
}

export interface FitDataset {
    /** A JSON array, JSON lines or CSV file, absolute or relative to the spec file, then to the working directory. */
    readonly file: string;
    /** Command in percent of full speed, after rescaling. */
    readonly duty: ColumnRef;
    /** Motor current in amperes, after rescaling. */
    readonly current: ColumnRef;
}

/**
 * Full scales of the device's feature normalisation: the model works in
 * normalised units (`physical / fullScale`), and the device declares the
 * same scales on its side, so the two must be written down together.
 */
export interface FullScale {
    readonly duty: number;
    readonly current: number;
    readonly senseSpan: number;
}

/** Validity domain of the affine model, in normalised duty; rows outside are left out of the fit. */
export interface FitDomain {
    readonly dutyMin: number;
    readonly dutyMax: number;
}

export interface FitOutputSettings {
    readonly dir?: string;
    /** Name of the ONNX file inside the output folder. */
    readonly file: string;
}

/**
 * What the artifact declares once installed as a monitor: the alarm on the
 * residual, exactly as the device's own output table states it. The thresholds
 * live here, in the monitor's specification, and are copied verbatim into
 * `contract.json`; `evaluate` judges the artifact against them and never
 * receives thresholds of its own (docs/architecture/usine-jobs.fr.md, decision 3).
 */
export interface MonitorSpec {
    readonly residual: {
        /** Alarm threshold on the residual, in normalised current. Must clear the model's worst-case error. */
        readonly threshold: number;
        /** Consecutive cycles above the threshold before the alarm is raised. */
        readonly debounceCycles: number;
        /** Severity handed to the alarm consumer (a number, not a band: the consumer sorts). */
        readonly severity: number;
        /** Alarm name, as the device publishes it. */
        readonly alarm: string;
    };
}

export interface FitSpec {
    readonly version: 1;
    readonly job: "fit";
    readonly name: string;
    /** Model family. `affine-residual` is the scrubber health model: expected = intercept + slope * duty, residual = |expected - current|. */
    readonly model: "affine-residual";
    readonly dataset: FitDataset;
    readonly fullScale: FullScale;
    readonly domain: FitDomain;
    readonly monitor: MonitorSpec;
    readonly outputs: FitOutputSettings;
}

/** A quantity the monitor needs, read from a node instance and rescaled to physical units (`value * scale + offset`). */
export interface GraphQuantity {
    readonly node: string;
    readonly property: string;
    readonly scale: number;
    readonly offset: number;
}

/** A setting applied at a simulated instant: the fault, as the oracle injects it. */
export interface Injection extends NodeSetting {
    /** Simulated time of the injection, in seconds from the start of the scenario. */
    readonly at: number;
}

/** What a scenario expects of the monitor: silence, or an alarm within a delay of the injection. */
export type ScenarioExpectation = { readonly alarms: 0 } | { readonly alarmWithin: number };

export interface Scenario {
    readonly name: string;
    /** Simulated duration, in seconds. */
    readonly duration: number;
    readonly inject: ReadonlyArray<Injection>;
    readonly expect: ScenarioExpectation;
}

export interface EvaluateRun {
    /** Tick period in simulated seconds. */
    readonly dt: number;
    /** Evaluation period of the monitor, in simulated seconds: the firmware's one-second cycle. */
    readonly cycle: number;
    /** Cycles before this time are not evaluated (the machine is starting). */
    readonly settle: number;
}

export interface EvaluateSpec {
    readonly version: 1;
    readonly job: "evaluate";
    readonly name: string;
    /** First form: a monitor judged against the oracle. */
    readonly kind: "monitor-vs-oracle";
    /** Model family of the artifact, which fixes how it is run and how its alarm is read. */
    readonly model: "affine-residual";
    readonly artifact: { readonly file: string; readonly contract: string };
    readonly graph: string;
    readonly run: EvaluateRun;
    /** Where the monitor's inputs come from in the graph, in physical units (percent, amperes). */
    readonly features: { readonly duty: GraphQuantity; readonly current: GraphQuantity };
    /** Applied to every scenario before anything else. */
    readonly operatingPoint: ReadonlyArray<NodeSetting>;
    readonly scenarios: ReadonlyArray<Scenario>;
    readonly outputs?: { readonly dir?: string };
}

export type JobSpec = SweepSpec | FitSpec | EvaluateSpec;

export class SpecError extends Error {
    public constructor(message: string) {
        super(message);
        this.name = "SpecError";
    }
}

function fail(path: string, message: string): never {
    throw new SpecError(`${path}: ${message}`);
}

function isRecord(x: unknown): x is Record<string, unknown> {
    return typeof x === "object" && x !== null && !Array.isArray(x);
}

function finite(x: unknown, path: string): number {
    if (typeof x !== "number" || !Number.isFinite(x)) fail(path, "expected a finite number");
    return x;
}

function positive(x: unknown, path: string): number {
    const v = finite(x, path);
    if (v <= 0) fail(path, "expected a number greater than zero");
    return v;
}

function text(x: unknown, path: string): string {
    if (typeof x !== "string" || x.length === 0) fail(path, "expected a non-empty string");
    return x;
}

function optionalText(x: unknown, path: string): string | undefined {
    return x === undefined ? undefined : text(x, path);
}

function array(x: unknown, path: string): ReadonlyArray<unknown> {
    if (!Array.isArray(x)) fail(path, "expected an array");
    return x;
}

function nodeRef(x: unknown, path: string): { node: string; property: string } {
    if (!isRecord(x)) fail(path, "expected an object");
    return { node: text(x.node, `${path}.node`), property: text(x.property, `${path}.property`) };
}

function parseSetting(x: unknown, path: string): NodeSetting {
    const ref = nodeRef(x, path);
    const r = x as Record<string, unknown>;
    if (!("value" in r)) fail(`${path}.value`, "missing");
    return { ...ref, value: r.value };
}

function parseAxis(x: unknown, path: string): GridAxis {
    const ref = nodeRef(x, path);
    const r = x as Record<string, unknown>;
    if (r.values !== undefined && r.range !== undefined) fail(path, "give either `values` or `range`, not both");
    if (r.values !== undefined) {
        const values = array(r.values, `${path}.values`);
        if (values.length === 0) fail(`${path}.values`, "expected at least one value");
        return { ...ref, values };
    }
    if (r.range !== undefined) {
        if (!isRecord(r.range)) fail(`${path}.range`, "expected an object");
        const from = finite(r.range.from, `${path}.range.from`);
        const to = finite(r.range.to, `${path}.range.to`);
        const step = positive(r.range.step, `${path}.range.step`);
        if (to < from) fail(`${path}.range`, "`to` must not be below `from`");
        return { ...ref, range: { from, to, step } };
    }
    return fail(path, "expected `values` or `range`");
}

function parseRecord(x: unknown, path: string): RecordField {
    const ref = nodeRef(x, path);
    const r = x as Record<string, unknown>;
    return { ...ref, as: optionalText(r.as, `${path}.as`) };
}

function parseFrequency(x: unknown, path: string): FrequencySource {
    if (!isRecord(x)) fail(path, "expected an object");
    if (x.hz !== undefined) return { hz: positive(x.hz, `${path}.hz`) };
    const fromField = text(x.fromField, `${path}.fromField`);
    const kind = x.kind ?? "angular";
    if (kind !== "angular" && kind !== "hz") fail(`${path}.kind`, 'expected "angular" or "hz"');
    return { fromField, kind };
}

const STATS: ReadonlyArray<SummaryStat["stat"]> = ["mean", "min", "max", "rms", "lockin"];

function parseSummary(x: unknown, path: string): SummaryStat {
    if (!isRecord(x)) fail(path, "expected an object");
    const field = text(x.field, `${path}.field`);
    const stat = x.stat;
    if (typeof stat !== "string" || !(STATS as ReadonlyArray<string>).includes(stat)) fail(`${path}.stat`, `expected one of ${STATS.join(", ")}`);
    const out: SummaryStat = { field, stat: stat as SummaryStat["stat"], as: optionalText(x.as, `${path}.as`) };
    if (stat === "lockin") {
        if (x.frequency === undefined) fail(`${path}.frequency`, "required for lockin");
        return { ...out, frequency: parseFrequency(x.frequency, `${path}.frequency`) };
    }
    return out;
}

/**
 * Validate a parsed JSON value as a job spec. Returns a frozen, fully typed
 * spec or throws a `SpecError` naming the first offending path.
 */
export function parseSpec(raw: unknown): JobSpec {
    if (!isRecord(raw)) fail("spec", "expected a JSON object");
    if (raw.version !== 1) fail("spec.version", "expected 1");
    if (typeof raw.job !== "string" || !(JOBS as ReadonlyArray<string>).includes(raw.job)) fail("spec.job", `expected one of ${JOBS.join(", ")}`);
    const name = text(raw.name, "spec.name");
    if (!/^[A-Za-z0-9._-]+$/.test(name)) fail("spec.name", "use letters, digits, dot, underscore or dash (it names a folder)");
    if (raw.job === "fit") return parseFitSpec(raw, name);
    if (raw.job === "evaluate") return parseEvaluateSpec(raw, name);
    return parseSweepSpec(raw, name);
}

const JOBS = ["sweep", "fit", "evaluate"] as const;

function parseGraphQuantity(x: unknown, path: string): GraphQuantity {
    const ref = nodeRef(x, path);
    const r = x as Record<string, unknown>;
    return {
        ...ref,
        scale: r.scale === undefined ? 1 : finite(r.scale, `${path}.scale`),
        offset: r.offset === undefined ? 0 : finite(r.offset, `${path}.offset`),
    };
}

function parseScenario(x: unknown, path: string): Scenario {
    if (!isRecord(x)) fail(path, "expected an object");
    const name = text(x.name, `${path}.name`);
    if (!/^[A-Za-z0-9._-]+$/.test(name)) fail(`${path}.name`, "use letters, digits, dot, underscore or dash (it names a trace file)");
    const duration = positive(x.duration, `${path}.duration`);
    const inject = (x.inject === undefined ? [] : array(x.inject, `${path}.inject`)).map((i, k) => {
        const setting = parseSetting(i, `${path}.inject[${k}]`);
        const at = finite((i as Record<string, unknown>).at, `${path}.inject[${k}].at`);
        if (at < 0 || at >= duration) fail(`${path}.inject[${k}].at`, "expected 0 <= at < duration");
        return { ...setting, at };
    });
    if (!isRecord(x.expect)) fail(`${path}.expect`, "expected { alarms: 0 } or { alarmWithin: seconds }");
    let expect: ScenarioExpectation;
    if (x.expect.alarms !== undefined) {
        if (x.expect.alarms !== 0) fail(`${path}.expect.alarms`, "only 0 is meaningful: a nominal scenario tolerates no alarm");
        if (inject.length > 0) fail(`${path}.expect`, "a scenario that injects a fault must expect an alarm (alarmWithin)");
        expect = { alarms: 0 };
    } else {
        const within = positive(x.expect.alarmWithin, `${path}.expect.alarmWithin`);
        if (inject.length === 0) fail(`${path}.expect`, "alarmWithin needs at least one injection to count from");
        expect = { alarmWithin: within };
    }
    return { name, duration, inject, expect };
}

function parseEvaluateSpec(raw: Record<string, unknown>, name: string): EvaluateSpec {
    if (raw.kind !== "monitor-vs-oracle") fail("spec.kind", 'expected "monitor-vs-oracle" (the only form built in this milestone)');
    if (raw.model !== "affine-residual") fail("spec.model", 'expected "affine-residual" (the only model family in this milestone)');
    if (!isRecord(raw.artifact)) fail("spec.artifact", "expected an object { file, contract }");
    const artifact = { file: text(raw.artifact.file, "spec.artifact.file"), contract: text(raw.artifact.contract, "spec.artifact.contract") };
    const graph = text(raw.graph, "spec.graph");
    if (!isRecord(raw.run)) fail("spec.run", "expected an object { dt, cycle, settle }");
    const dt = positive(raw.run.dt, "spec.run.dt");
    const cycle = raw.run.cycle === undefined ? 1 : positive(raw.run.cycle, "spec.run.cycle");
    const settle = raw.run.settle === undefined ? 0 : finite(raw.run.settle, "spec.run.settle");
    if (settle < 0) fail("spec.run.settle", "expected a non-negative number");
    if (cycle < dt) fail("spec.run.cycle", "a cycle cannot be shorter than a tick");
    if (!isRecord(raw.features)) fail("spec.features", "expected an object { duty, current }");
    const features = { duty: parseGraphQuantity(raw.features.duty, "spec.features.duty"), current: parseGraphQuantity(raw.features.current, "spec.features.current") };
    const operatingPoint = raw.operatingPoint === undefined ? [] : array(raw.operatingPoint, "spec.operatingPoint").map((s, i) => parseSetting(s, `spec.operatingPoint[${i}]`));
    const scenarios = array(raw.scenarios, "spec.scenarios").map((s, i) => parseScenario(s, `spec.scenarios[${i}]`));
    if (scenarios.length === 0) fail("spec.scenarios", "expected at least one scenario");
    const names = new Set<string>();
    for (const [i, s] of scenarios.entries()) {
        if (names.has(s.name)) fail(`spec.scenarios[${i}].name`, `duplicate scenario "${s.name}"`);
        names.add(s.name);
        if ("alarmWithin" in s.expect) {
            const last = Math.max(...s.inject.map((j) => j.at));
            if (last + s.expect.alarmWithin > s.duration) fail(`spec.scenarios[${i}].expect.alarmWithin`, "the deadline falls after the end of the scenario");
        }
    }
    let outputs: { dir?: string } | undefined;
    if (raw.outputs !== undefined) {
        if (!isRecord(raw.outputs)) fail("spec.outputs", "expected an object");
        outputs = { dir: optionalText(raw.outputs.dir, "spec.outputs.dir") };
    }
    return Object.freeze({
        version: 1,
        job: "evaluate",
        name,
        kind: "monitor-vs-oracle",
        model: "affine-residual",
        artifact,
        graph,
        run: { dt, cycle, settle },
        features,
        operatingPoint,
        scenarios,
        outputs,
    });
}

function parseColumnRef(x: unknown, path: string): ColumnRef {
    if (typeof x === "string") return { column: text(x, path), scale: 1, offset: 0 };
    if (!isRecord(x)) fail(path, "expected a column name or { column, scale?, offset? }");
    return {
        column: text(x.column, `${path}.column`),
        scale: x.scale === undefined ? 1 : finite(x.scale, `${path}.scale`),
        offset: x.offset === undefined ? 0 : finite(x.offset, `${path}.offset`),
    };
}

function parseFitSpec(raw: Record<string, unknown>, name: string): FitSpec {
    if (raw.model !== "affine-residual") fail("spec.model", 'expected "affine-residual" (the only model family in this milestone)');
    if (!isRecord(raw.dataset)) fail("spec.dataset", "expected an object");
    const dataset: FitDataset = {
        file: text(raw.dataset.file, "spec.dataset.file"),
        duty: parseColumnRef(raw.dataset.duty, "spec.dataset.duty"),
        current: parseColumnRef(raw.dataset.current, "spec.dataset.current"),
    };
    if (!isRecord(raw.fullScale)) fail("spec.fullScale", "expected an object { duty, current, senseSpan }");
    const fullScale: FullScale = {
        duty: positive(raw.fullScale.duty, "spec.fullScale.duty"),
        current: positive(raw.fullScale.current, "spec.fullScale.current"),
        senseSpan: positive(raw.fullScale.senseSpan, "spec.fullScale.senseSpan"),
    };
    if (!isRecord(raw.domain)) fail("spec.domain", "expected an object { dutyMin, dutyMax } in normalised duty");
    const domain: FitDomain = { dutyMin: finite(raw.domain.dutyMin, "spec.domain.dutyMin"), dutyMax: finite(raw.domain.dutyMax, "spec.domain.dutyMax") };
    if (domain.dutyMin < 0 || domain.dutyMax > 1 || domain.dutyMin >= domain.dutyMax) fail("spec.domain", "expected 0 <= dutyMin < dutyMax <= 1");
    if (!isRecord(raw.outputs)) fail("spec.outputs", "expected an object with at least { file }");
    const file = text(raw.outputs.file, "spec.outputs.file");
    if (!/^[A-Za-z0-9._-]+\.onnx$/.test(file)) fail("spec.outputs.file", "expected a plain file name ending in .onnx");
    const outputs: FitOutputSettings = { dir: optionalText(raw.outputs.dir, "spec.outputs.dir"), file };
    const monitor = parseMonitor(raw.monitor, "spec.monitor");
    return Object.freeze({ version: 1, job: "fit", name, model: "affine-residual", dataset, fullScale, domain, monitor, outputs });
}

function nonNegativeInteger(x: unknown, path: string): number {
    const v = finite(x, path);
    if (v < 0 || !Number.isInteger(v)) fail(path, "expected a non-negative integer");
    return v;
}

function parseMonitor(x: unknown, path: string): MonitorSpec {
    if (!isRecord(x)) fail(path, "expected an object { residual: { threshold, debounceCycles, severity, alarm } }");
    if (!isRecord(x.residual)) fail(`${path}.residual`, "expected an object { threshold, debounceCycles, severity, alarm }");
    const r = x.residual;
    return {
        residual: {
            threshold: positive(r.threshold, `${path}.residual.threshold`),
            debounceCycles: nonNegativeInteger(r.debounceCycles, `${path}.residual.debounceCycles`),
            severity: nonNegativeInteger(r.severity, `${path}.residual.severity`),
            alarm: text(r.alarm, `${path}.residual.alarm`),
        },
    };
}

function parseSweepSpec(raw: Record<string, unknown>, name: string): SweepSpec {
    const graph = text(raw.graph, "spec.graph");

    if (!isRecord(raw.run)) fail("spec.run", "expected an object");
    const dt = positive(raw.run.dt, "spec.run.dt");
    const duration = positive(raw.run.duration, "spec.run.duration");
    const settle = raw.run.settle === undefined ? 0 : finite(raw.run.settle, "spec.run.settle");
    if (settle < 0 || settle >= duration) fail("spec.run.settle", "expected 0 <= settle < duration");

    const set = raw.set === undefined ? [] : array(raw.set, "spec.set").map((s, i) => parseSetting(s, `spec.set[${i}]`));
    const grid = raw.grid === undefined ? [] : array(raw.grid, "spec.grid").map((a, i) => parseAxis(a, `spec.grid[${i}]`));
    const record = array(raw.record, "spec.record").map((r, i) => parseRecord(r, `spec.record[${i}]`));
    if (record.length === 0) fail("spec.record", "expected at least one field to record");

    const columns = new Set<string>();
    for (const [i, r] of record.entries()) {
        const column = recordColumn(r);
        if (columns.has(column)) fail(`spec.record[${i}]`, `duplicate column "${column}"`);
        columns.add(column);
    }
    const summary = raw.summary === undefined ? [] : array(raw.summary, "spec.summary").map((s, i) => parseSummary(s, `spec.summary[${i}]`));
    for (const [i, s] of summary.entries()) {
        if (!columns.has(s.field)) fail(`spec.summary[${i}].field`, `"${s.field}" is not a recorded column (${[...columns].join(", ")})`);
        const f = s.frequency;
        if (f && "fromField" in f && !columns.has(f.fromField)) fail(`spec.summary[${i}].frequency.fromField`, `"${f.fromField}" is not a recorded column`);
    }

    let outputs: OutputSettings = {};
    if (raw.outputs !== undefined) {
        if (!isRecord(raw.outputs)) fail("spec.outputs", "expected an object");
        const samples = raw.outputs.samples;
        if (samples !== undefined && typeof samples !== "boolean") fail("spec.outputs.samples", "expected a boolean");
        outputs = { dir: optionalText(raw.outputs.dir, "spec.outputs.dir"), samples: samples as boolean | undefined };
    }

    return Object.freeze({ version: 1, job: "sweep", name, graph, run: { dt, duration, settle }, set, grid, record, summary, outputs });
}

/** Column name of a recorded field in every output. */
export function recordColumn(field: RecordField): string {
    return field.as ?? `${field.node}.${field.property}`;
}

/** Column name of a summary statistic. */
export function summaryColumn(stat: SummaryStat): string {
    return stat.as ?? `${stat.field}_${stat.stat}`;
}

/** Expand an axis to its concrete values. */
export function axisValues(axis: GridAxis): ReadonlyArray<unknown> {
    if (axis.values) return axis.values;
    const { from, to, step } = axis.range!;
    const out: number[] = [];
    // Count the steps first so accumulated rounding never drops the last value.
    const n = Math.floor((to - from) / step + 1e-9);
    for (let k = 0; k <= n; k++) out.push(from + k * step);
    return out;
}

/** Cartesian product of the grid, one setting list per point, first axis slowest. */
export function gridPoints(grid: ReadonlyArray<GridAxis>): ReadonlyArray<ReadonlyArray<NodeSetting>> {
    let points: NodeSetting[][] = [[]];
    for (const axis of grid) {
        const next: NodeSetting[][] = [];
        for (const point of points) {
            for (const value of axisValues(axis)) next.push([...point, { node: axis.node, property: axis.property, value }]);
        }
        points = next;
    }
    return points;
}
