/**
 * ONNX operator conformance tests.
 *
 * Compares SpikeyPanda operator outputs against reference vectors
 * generated by onnxruntime (via generate_vectors.py).
 */
import * as fs from "fs";
import * as path from "path";
import type { ITensor } from "../../dev/runtime/src/compute/compute.interfaces";
import { OnnxOpRegistry } from "../../dev/runtime/src/onnx/registry";
import { makeTensor } from "../../dev/runtime/src/onnx/registry";
import { registerMathOps } from "../../dev/runtime/src/onnx/ops/math";
import { registerActivationOps } from "../../dev/runtime/src/onnx/ops/activations";
import { registerMatrixOps } from "../../dev/runtime/src/onnx/ops/matrix";
import { registerConvOps } from "../../dev/runtime/src/onnx/ops/conv";
import { registerNormOps } from "../../dev/runtime/src/onnx/ops/normalization";
import { registerRecurrentOps } from "../../dev/runtime/src/onnx/ops/recurrent";
import { registerMiscOps } from "../../dev/runtime/src/onnx/ops/misc";

// ---------------------------------------------------------------------------
// Types for test vectors
// ---------------------------------------------------------------------------

interface TensorVector {
    name: string;
    shape: number[];
    data: number[];
}

interface TestCase {
    opType: string;
    inputs: TensorVector[];
    outputs: TensorVector[];
    attributes?: Record<string, number | number[]>;
}

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------

const VECTORS_PATH = path.resolve(__dirname, "test-vectors.json");

let testCases: TestCase[] = [];
let registry: OnnxOpRegistry;

function toTensor(v: TensorVector): ITensor {
    return {
        data: new Float32Array(v.data),
        shape: [...v.shape],
        name: v.name,
    };
}

function buildAttributes(attrs?: Record<string, number | number[]>): Map<string, number> {
    const map = new Map<string, number>();
    if (!attrs) return map;
    for (const [k, v] of Object.entries(attrs)) {
        if (typeof v === "number") {
            map.set(k, v);
        }
        // arrays (like perm) are stored as individual values; the op reads them via attrInt
        // For simplicity, store the first element for single-value attrs
    }
    return map;
}

// ---------------------------------------------------------------------------
// Load vectors and create registry
// ---------------------------------------------------------------------------

beforeAll(() => {
    if (!fs.existsSync(VECTORS_PATH)) {
        throw new Error(
            `Test vectors not found at ${VECTORS_PATH}.\n` +
            `Run: python packages/tests/onnx-ops/generate_vectors.py`,
        );
    }
    testCases = JSON.parse(fs.readFileSync(VECTORS_PATH, "utf-8"));

    registry = new OnnxOpRegistry();
    registerMathOps(registry);
    registerActivationOps(registry);
    registerMatrixOps(registry);
    registerConvOps(registry);
    registerNormOps(registry);
    registerRecurrentOps(registry);
    registerMiscOps(registry);
});

// ---------------------------------------------------------------------------
// Tolerance helper
// ---------------------------------------------------------------------------

const DEFAULT_ATOL = 1e-4;
const DEFAULT_RTOL = 1e-4;

function assertClose(actual: Float32Array, expected: Float32Array, opType: string, atol = DEFAULT_ATOL, rtol = DEFAULT_RTOL) {
    expect(actual.length).toBe(expected.length);
    for (let i = 0; i < expected.length; i++) {
        const diff = Math.abs(actual[i] - expected[i]);
        const tol = atol + rtol * Math.abs(expected[i]);
        if (diff > tol) {
            throw new Error(
                `${opType} mismatch at index ${i}: got ${actual[i]}, expected ${expected[i]} (diff=${diff}, tol=${tol})`,
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("ONNX Ops vs onnxruntime reference", () => {
    // Map of opType to special handling for node creation
    // Most ops use the standard factory; some need tweaks

    it("should have test vectors loaded", () => {
        expect(testCases.length).toBeGreaterThan(0);
        console.log(`Loaded ${testCases.length} test vectors`);
    });

    it("should have all referenced ops registered", () => {
        for (const tc of testCases) {
            expect(registry.has(tc.opType)).toBe(true);
        }
    });

    // Generate one test per operator
    const vectorsRaw = fs.existsSync(path.resolve(__dirname, "test-vectors.json"))
        ? JSON.parse(fs.readFileSync(path.resolve(__dirname, "test-vectors.json"), "utf-8")) as TestCase[]
        : [];

    for (const tc of vectorsRaw) {
        it(`${tc.opType} — SpikeyPanda matches onnxruntime`, () => {
            const inputs = tc.inputs.map(toTensor);
            const expectedOutputs = tc.outputs.map(toTensor);

            // Build a minimal OnnxNodeInfo
            const nodeInfo = {
                opType: tc.opType,
                inputs: tc.inputs.map((inp) => inp.name),
                outputs: tc.outputs.map((out) => out.name),
                attributes: buildAttributes(tc.attributes),
            };

            // Create the node via registry
            const emptyInitializers = new Map();
            const node = registry.create(nodeInfo as any, emptyInitializers);

            // Execute
            const actualOutputs = (node as any).execute(inputs);

            // Compare each output
            expect(actualOutputs.length).toBeGreaterThanOrEqual(expectedOutputs.length);
            for (let i = 0; i < expectedOutputs.length; i++) {
                const actual = actualOutputs[i] as ITensor;
                const expected = expectedOutputs[i];

                // Shape check
                expect(actual.shape).toEqual(expected.shape);

                // Value check
                assertClose(actual.data, expected.data, tc.opType);
            }
        });
    }
});

// ---------------------------------------------------------------------------
// Raw computation tests (direct math, no SpikeyPanda node)
// ---------------------------------------------------------------------------

describe("Raw computation sanity checks", () => {
    const vectorsRaw = fs.existsSync(path.resolve(__dirname, "test-vectors.json"))
        ? JSON.parse(fs.readFileSync(path.resolve(__dirname, "test-vectors.json"), "utf-8")) as TestCase[]
        : [];

    function rawCompute(opType: string, inputs: ITensor[], attrs?: Record<string, number | number[]>): ITensor | null {
        const A = inputs[0];
        switch (opType) {
            case "Relu": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = Math.max(0, A.data[i]);
                return makeTensor(out, [...A.shape]);
            }
            case "Sigmoid": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = 1 / (1 + Math.exp(-A.data[i]));
                return makeTensor(out, [...A.shape]);
            }
            case "Tanh": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = Math.tanh(A.data[i]);
                return makeTensor(out, [...A.shape]);
            }
            case "Exp": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = Math.exp(A.data[i]);
                return makeTensor(out, [...A.shape]);
            }
            case "Log": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = Math.log(A.data[i]);
                return makeTensor(out, [...A.shape]);
            }
            case "Sqrt": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = Math.sqrt(A.data[i]);
                return makeTensor(out, [...A.shape]);
            }
            case "Abs": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = Math.abs(A.data[i]);
                return makeTensor(out, [...A.shape]);
            }
            case "Neg": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = -A.data[i];
                return makeTensor(out, [...A.shape]);
            }
            case "Atan": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = Math.atan(A.data[i]);
                return makeTensor(out, [...A.shape]);
            }
            case "Add": {
                const B = inputs[1];
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = A.data[i] + B.data[i];
                return makeTensor(out, [...A.shape]);
            }
            case "Sub": {
                const B = inputs[1];
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = A.data[i] - B.data[i];
                return makeTensor(out, [...A.shape]);
            }
            case "Mul": {
                const B = inputs[1];
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = A.data[i] * B.data[i];
                return makeTensor(out, [...A.shape]);
            }
            case "Div": {
                const B = inputs[1];
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = A.data[i] / B.data[i];
                return makeTensor(out, [...A.shape]);
            }
            case "MatMul": {
                const B = inputs[1];
                const M = A.shape[0], K = A.shape[1], N = B.shape[1];
                const out = new Float32Array(M * N);
                for (let m = 0; m < M; m++) {
                    for (let n = 0; n < N; n++) {
                        let sum = 0;
                        for (let k = 0; k < K; k++) {
                            sum += A.data[m * K + k] * B.data[k * N + n];
                        }
                        out[m * N + n] = sum;
                    }
                }
                return makeTensor(out, [M, N]);
            }
            case "Identity":
                return makeTensor(new Float32Array(A.data), [...A.shape]);
            default:
                return null; // no raw implementation for this op
        }
    }

    for (const tc of vectorsRaw) {
        const inputs = tc.inputs.map(toTensor);
        const rawResult = rawCompute(tc.opType, inputs, tc.attributes);
        if (rawResult === null) continue; // skip ops without raw impl

        it(`${tc.opType} — raw JS matches onnxruntime`, () => {
            const expected = toTensor(tc.outputs[0]);
            expect(rawResult.shape).toEqual(expected.shape);
            assertClose(rawResult.data, expected.data, `raw_${tc.opType}`);
        });
    }
});
