/**
 * ONNX operator conformance tests.
 *
 * Compares SpikyPanda operator outputs against reference vectors
 * generated by onnxruntime (via generate_vectors.py).
 */
import * as fs from "fs";
import * as path from "path";
import type { ITensor } from "../../dev/runtime/src/compute/compute.interfaces";
import { OnnxOpRegistry } from "../../dev/runtime/src/onnx/registry";
import { makeTensor } from "../../dev/runtime/src/onnx/registry";
import { registerMathOps } from "../../dev/runtime/src/onnx/ops/math";
import { registerActivationOps } from "../../dev/runtime/src/onnx/ops/activations";
import { registerMatrixOps } from "../../dev/runtime/src/onnx/ops/matrix";
import { registerConvOps } from "../../dev/runtime/src/onnx/ops/conv";
import { registerNormOps } from "../../dev/runtime/src/onnx/ops/normalization";
import { registerRecurrentOps } from "../../dev/runtime/src/onnx/ops/recurrent";
import { registerMiscOps } from "../../dev/runtime/src/onnx/ops/misc";
import { registerSpikyPandaOps } from "../../dev/runtime/src/onnx/ops/spikypanda";
import { OnnxParser } from "../../dev/runtime/src/onnx/onnx-parser";
import { OnnxGraphBuilder } from "../../dev/runtime/src/onnx/graph-builder";

// ---------------------------------------------------------------------------
// Types for test vectors
// ---------------------------------------------------------------------------

interface TensorVector {
    name: string;
    shape: number[];
    data: number[];
}

interface TestCase {
    opType: string;
    inputs: TensorVector[];
    outputs: TensorVector[];
    attributes?: Record<string, number | number[]>;
    modelFile?: string;
    feeds?: TensorVector[];
}

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------

const VECTORS_PATH = path.resolve(__dirname, "test-vectors.json");

let testCases: TestCase[] = [];
let registry: OnnxOpRegistry;        // generic ops only
let spRegistry: OnnxOpRegistry;      // generic + SpikyPanda native overrides

function toTensor(v: TensorVector): ITensor {
    return {
        data: new Float32Array(v.data),
        shape: [...v.shape],
        name: v.name,
    };
}

function buildAttributes(attrs?: Record<string, number | number[]>): Map<string, number> {
    const map = new Map<string, number>();
    if (!attrs) return map;
    for (const [k, v] of Object.entries(attrs)) {
        if (typeof v === "number") {
            map.set(k, v);
        }
        // arrays (like perm) are stored as individual values; the op reads them via attrInt
        // For simplicity, store the first element for single-value attrs
    }
    return map;
}

// ---------------------------------------------------------------------------
// Load vectors and create registry
// ---------------------------------------------------------------------------

beforeAll(() => {
    if (!fs.existsSync(VECTORS_PATH)) {
        throw new Error(
            `Test vectors not found at ${VECTORS_PATH}.\n` +
            `Run: python packages/tests/onnx-ops/generate_vectors.py`,
        );
    }
    testCases = JSON.parse(fs.readFileSync(VECTORS_PATH, "utf-8"));

    registry = new OnnxOpRegistry();
    registerMathOps(registry);
    registerActivationOps(registry);
    registerMatrixOps(registry);
    registerConvOps(registry);
    registerNormOps(registry);
    registerRecurrentOps(registry);
    registerMiscOps(registry);

    spRegistry = new OnnxOpRegistry();
    registerMathOps(spRegistry);
    registerActivationOps(spRegistry);
    registerMatrixOps(spRegistry);
    registerConvOps(spRegistry);
    registerNormOps(spRegistry);
    registerRecurrentOps(spRegistry);
    registerMiscOps(spRegistry);
    registerSpikyPandaOps(spRegistry);
});

// ---------------------------------------------------------------------------
// Tolerance helper
// ---------------------------------------------------------------------------

const DEFAULT_ATOL = 1e-4;
const DEFAULT_RTOL = 1e-4;

function assertClose(actual: Float32Array, expected: Float32Array, opType: string, atol = DEFAULT_ATOL, rtol = DEFAULT_RTOL) {
    expect(actual.length).toBe(expected.length);
    for (let i = 0; i < expected.length; i++) {
        const diff = Math.abs(actual[i] - expected[i]);
        const tol = atol + rtol * Math.abs(expected[i]);
        if (diff > tol) {
            throw new Error(
                `${opType} mismatch at index ${i}: got ${actual[i]}, expected ${expected[i]} (diff=${diff}, tol=${tol})`,
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

// Ops that only work in graph pipeline (no inputs, everything from attributes)
const GRAPH_ONLY_OPS = new Set(["Constant"]);

// ---------------------------------------------------------------------------
// Helper: run a single op through a given registry and compare to reference
// ---------------------------------------------------------------------------

function testOpWithRegistry(tc: TestCase, reg: OnnxOpRegistry) {
    const inputs = tc.inputs.map(toTensor);
    const expectedOutputs = tc.outputs.map(toTensor);

    const nodeInfo = {
        opType: tc.opType,
        inputs: tc.inputs.map((inp) => inp.name),
        outputs: tc.outputs.map((out) => out.name),
        attributes: buildAttributes(tc.attributes),
    };

    const node = reg.create(nodeInfo as any, new Map());
    const actualOutputs = (node as any).execute(inputs);

    expect(actualOutputs.length).toBeGreaterThanOrEqual(expectedOutputs.length);
    for (let i = 0; i < expectedOutputs.length; i++) {
        const actual = actualOutputs[i] as ITensor;
        const expected = expectedOutputs[i];
        expect(actual.shape).toEqual(expected.shape);
        assertClose(actual.data, expected.data, tc.opType);
    }
}

// ---------------------------------------------------------------------------
// Generic ONNX ops vs onnxruntime reference
// ---------------------------------------------------------------------------

describe("Generic ONNX ops vs onnxruntime", () => {
    it("should have test vectors loaded", () => {
        expect(testCases.length).toBeGreaterThan(0);
        console.log(`Loaded ${testCases.length} test vectors`);
    });

    const vectorsRaw = fs.existsSync(path.resolve(__dirname, "test-vectors.json"))
        ? JSON.parse(fs.readFileSync(path.resolve(__dirname, "test-vectors.json"), "utf-8")) as TestCase[]
        : [];

    for (const tc of vectorsRaw) {
        if (GRAPH_ONLY_OPS.has(tc.opType)) continue;
        it(`${tc.opType} — generic op matches onnxruntime`, () => {
            testOpWithRegistry(tc, registry);
        });
    }
});

// ---------------------------------------------------------------------------
// SpikyPanda native ops vs onnxruntime reference
// ---------------------------------------------------------------------------

describe("SpikyPanda native ops vs onnxruntime", () => {
    const vectorsRaw = fs.existsSync(path.resolve(__dirname, "test-vectors.json"))
        ? JSON.parse(fs.readFileSync(path.resolve(__dirname, "test-vectors.json"), "utf-8")) as TestCase[]
        : [];

    for (const tc of vectorsRaw) {
        if (GRAPH_ONLY_OPS.has(tc.opType)) continue;
        it(`${tc.opType} — spikypanda op matches onnxruntime [spikypanda]`, () => {
            testOpWithRegistry(tc, spRegistry);
        });
    }
});

// ---------------------------------------------------------------------------
// Raw computation tests (direct math, no SpikeyPanda node)
// ---------------------------------------------------------------------------

describe("Raw computation sanity checks", () => {
    const vectorsRaw = fs.existsSync(path.resolve(__dirname, "test-vectors.json"))
        ? JSON.parse(fs.readFileSync(path.resolve(__dirname, "test-vectors.json"), "utf-8")) as TestCase[]
        : [];

    function rawCompute(opType: string, inputs: ITensor[], attrs?: Record<string, number | number[]>): ITensor | null {
        const A = inputs[0];
        switch (opType) {
            case "Relu": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = Math.max(0, A.data[i]);
                return makeTensor(out, [...A.shape]);
            }
            case "Sigmoid": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = 1 / (1 + Math.exp(-A.data[i]));
                return makeTensor(out, [...A.shape]);
            }
            case "Tanh": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = Math.tanh(A.data[i]);
                return makeTensor(out, [...A.shape]);
            }
            case "Exp": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = Math.exp(A.data[i]);
                return makeTensor(out, [...A.shape]);
            }
            case "Log": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = Math.log(A.data[i]);
                return makeTensor(out, [...A.shape]);
            }
            case "Sqrt": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = Math.sqrt(A.data[i]);
                return makeTensor(out, [...A.shape]);
            }
            case "Abs": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = Math.abs(A.data[i]);
                return makeTensor(out, [...A.shape]);
            }
            case "Neg": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = -A.data[i];
                return makeTensor(out, [...A.shape]);
            }
            case "Atan": {
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = Math.atan(A.data[i]);
                return makeTensor(out, [...A.shape]);
            }
            case "Add": {
                const B = inputs[1];
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = A.data[i] + B.data[i];
                return makeTensor(out, [...A.shape]);
            }
            case "Sub": {
                const B = inputs[1];
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = A.data[i] - B.data[i];
                return makeTensor(out, [...A.shape]);
            }
            case "Mul": {
                const B = inputs[1];
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = A.data[i] * B.data[i];
                return makeTensor(out, [...A.shape]);
            }
            case "Div": {
                const B = inputs[1];
                const out = new Float32Array(A.data.length);
                for (let i = 0; i < A.data.length; i++) out[i] = A.data[i] / B.data[i];
                return makeTensor(out, [...A.shape]);
            }
            case "MatMul": {
                const B = inputs[1];
                const M = A.shape[0], K = A.shape[1], N = B.shape[1];
                const out = new Float32Array(M * N);
                for (let m = 0; m < M; m++) {
                    for (let n = 0; n < N; n++) {
                        let sum = 0;
                        for (let k = 0; k < K; k++) {
                            sum += A.data[m * K + k] * B.data[k * N + n];
                        }
                        out[m * N + n] = sum;
                    }
                }
                return makeTensor(out, [M, N]);
            }
            case "Identity":
                return makeTensor(new Float32Array(A.data), [...A.shape]);
            default:
                return null; // no raw implementation for this op
        }
    }

    for (const tc of vectorsRaw) {
        const inputs = tc.inputs.map(toTensor);
        const rawResult = rawCompute(tc.opType, inputs, tc.attributes);
        if (rawResult === null) continue; // skip ops without raw impl

        it(`${tc.opType} — raw JS matches onnxruntime`, () => {
            const expected = toTensor(tc.outputs[0]);
            expect(rawResult.shape).toEqual(expected.shape);
            assertClose(rawResult.data, expected.data, `raw_${tc.opType}`);
        });
    }
});

// ---------------------------------------------------------------------------
// Graph pipeline tests (OnnxParser -> OnnxGraphBuilder -> graph.run)
//
// This tests the full SpikyPanda ONNX pipeline: parse a real .onnx binary,
// build a ComputeGraph via the graph builder, feed external inputs, run the
// graph, and compare outputs to onnxruntime reference.
// ---------------------------------------------------------------------------

describe("SpikyPanda graph pipeline vs onnxruntime reference", () => {
    const modelsDir = path.resolve(__dirname, "models");
    const vectorsRaw = fs.existsSync(path.resolve(__dirname, "test-vectors.json"))
        ? JSON.parse(fs.readFileSync(path.resolve(__dirname, "test-vectors.json"), "utf-8")) as TestCase[]
        : [];

    // Only test cases that have a modelFile and feeds
    const graphCases = vectorsRaw.filter(
        (tc) => tc.modelFile && fs.existsSync(path.join(modelsDir, tc.modelFile!)),
    );

    it("should have .onnx model files for graph tests", () => {
        expect(graphCases.length).toBeGreaterThan(0);
        console.log(`Graph pipeline: ${graphCases.length} models available`);
    });

    for (const tc of graphCases) {
        it(`${tc.opType} — graph pipeline matches onnxruntime`, () => {
            // 1. Read and parse the .onnx binary
            const modelPath = path.join(modelsDir, tc.modelFile!);
            const modelBytes = new Uint8Array(fs.readFileSync(modelPath));
            const parsed = OnnxParser.parse(modelBytes);
            expect(parsed).not.toBeNull();

            // 2. Build compute graph
            const builder = new OnnxGraphBuilder(registry);
            const { graph, inputNames } = builder.build(parsed!);
            expect(graph).toBeDefined();

            // 3. Prepare external inputs from feeds (or inputs if no feeds)
            const feedData = tc.feeds ?? tc.inputs;
            const externalInputs = new Map<string, ITensor>();
            for (const feed of feedData) {
                // Only feed tensors that are listed as graph inputs (not initializers)
                if (inputNames.includes(feed.name)) {
                    externalInputs.set(feed.name, toTensor(feed));
                }
            }

            // 4. Run the graph
            const results = graph.run(externalInputs);
            expect(results.size).toBeGreaterThan(0);

            // 5. Compare outputs
            const expectedOutputs = tc.outputs.map(toTensor);

            // Collect result tensors (may be keyed by various names)
            const resultTensors = [...results.values()];
            expect(resultTensors.length).toBeGreaterThanOrEqual(expectedOutputs.length);

            for (let i = 0; i < expectedOutputs.length; i++) {
                const actual = resultTensors[i];
                const expected = expectedOutputs[i];

                // Value check (shape may differ slightly in graph context due to
                // how the graph distributes outputs, so focus on data)
                expect(actual.data.length).toBe(expected.data.length);
                assertClose(actual.data, expected.data, `graph_${tc.opType}`);
            }
        });
    }
});
